DEBUG expanding frames of ctx, current size: 0

[Frame   0]
===========
> 01-assign.asm (Func)
  Constants:
    [  0] "a" (String)
    [  1] 5 (Int)

  Variables:
    a = 5 (Int)

  Stack:
    [  0] 5 (Int)
sp->[  1] [Nil]

  Instructions:
    [  0] PUSH K    1 ; 5 (Int)
    [  1] POP  V    0 ; var a
    [  2] PUSH V    0 ; var a
    [  3] DUMP S    1
pc->[  4] RET  _    0
    



= 5 (runtime.Int)
