DEBUG expanding frames of ctx, current size: 0

[Frame   0]
===========
> 09-if-cond-ands.agora (Func)
  Constants:
    [  0] "a" (String)
    [  1] true (Bool)
    [  2] 3 (Int)
    [  3] 5 (Int)
    [  4] 4 (Int)
    [  5] "foo" (String)
    [  6] "bar" (String)
    [  7] 1 (Int)
    [  8] -1 (Int)

  Variables:
    a = true (Bool)

  Stack:
    [  0] 1 (Int)
sp->[  1] [Nil]

  Instructions:
    [  6] GT   _    0
    [  7] PUSH K    5 ; "foo" (String)
    [  8] PUSH K    6 ; "bar" (String)
    [  9] GT   _    0
    [ 10] AND  _    0
    [ 11] PUSH V    0 ; var a
    [ 12] AND  _    0
    [ 13] TEST J    3
    [ 14] PUSH K    7 ; 1 (Int)
    [ 15] DUMP S    1
pc->[ 16] RET  _    0
    [ 17] PUSH K    8 ; -1 (Int)
    [ 18] DUMP S    1
    [ 19] RET  _    0
    

PASS - 1
