DEBUG expanding frames of ctx, current size: 0

[Frame   0]
===========
> 15-deep-object.agora (Func)
  Constants:
    [  0] "a" (String)
    [  1] "b" (String)
    [  2] "c" (String)
    [  3] "d" (String)
    [  4] "allo" (String)

  Variables:
    a = { "b" (String): { "c" (String): { "d" (String): "allo" (String), } (Object), } (Object), } (Object)

  Stack:
    [  0] "allo" (String)
sp->[  1] [Nil]

  Instructions:
    [ 18] GFLD _    0
    [ 19] SFLD _    0
    [ 20] PUSH K    3 ; "d" (String)
    [ 21] PUSH K    2 ; "c" (String)
    [ 22] PUSH K    1 ; "b" (String)
    [ 23] PUSH V    0 ; var a
    [ 24] GFLD _    0
    [ 25] GFLD _    0
    [ 26] GFLD _    0
    [ 27] DUMP S    1
pc->[ 28] RET  _    0
    

PASS - allo
