DEBUG expanding frames of ctx, current size: 0

[Frame   0]
===========
> <main> (Func)
  Constants:
    [  0] "a" (String)
    [  1] 7 (Int)
    [  2] "b" (String)
    [  3] 10 (Int)
    [  4] "add" (String)
    [  5] "sub" (String)
    [  6] "mul" (String)
    [  7] "div" (String)
    [  8] "mod" (String)
    [  9] "pow" (String)
    [ 10] "not" (String)
    [ 11] "unm" (String)

  Variables:
    a = 7 (Int)
    add = 17 (Int)
    b = 10 (Int)
    div = 0 (Int)
    mod = 3 (Int)
    mul = 70 (Int)
    not = false (Bool)
    pow = 282475249 (Int)
    sub = -3 (Int)
    unm = -7 (Int)

  Stack:
    [  0] [Nil]
sp->[  1] [Nil]

  Instructions:
    [ 26] POW  _    0
    [ 27] POP  V    9 ; var pow
    [ 28] PUSH V    0 ; var a
    [ 29] NOT  _    0
    [ 30] POP  V   10 ; var not
    [ 31] PUSH V    0 ; var a
    [ 32] UNM  _    0
    [ 33] POP  V   11 ; var unm
    [ 34] PUSH N    0 ; [Nil]
    [ 35] DUMP S    1
pc->[ 36] RET  _    0
    

PASS - nil