DEBUG expanding frames of ctx, current size: 0
DEBUG expanding frames of ctx, current size: 1
0
1
DEBUG expanding stack of func 06-loop-for-range.goblin, current size: 4
2
3
4
5
DEBUG expanding stack of func 06-loop-for-range.goblin, current size: 8
6
7
8
9

[Frame   0]
===========
> 06-loop-for-range.goblin (Func)
  Constants:
    [  0] "fmt" (String)
    [  1] "i" (String)
    [  2] 0 (Int)
    [  3] 1 (Int)
    [  4] 10 (Int)
    [  5] "Println" (String)

  Variables:
    fmt = { "Println" (String): fmt.Println (Func),  "Printf" (String): fmt.Printf (Func), } (Object)
    i = 10 (Int)

  Stack:
    [  6] 2 (Int)
    [  7] 2 (Int)
    [  8] 2 (Int)
    [  9] 2 (Int)
    [ 10] [Nil]
sp->[ 11] [Nil]

  Instructions:
    [  9] PUSH K    5 ; "Println" (String)
    [ 10] PUSH V    0 ; var fmt
    [ 11] CFLD A    1
    [ 12] PUSH V    1 ; var i
    [ 13] PUSH K    3 ; 1 (Int)
    [ 14] ADD  _    0
    [ 15] POP  V    1 ; var i
    [ 16] JMPB J   12
    [ 17] PUSH N    0 ; [Nil]
    [ 18] DUMP S    1
pc->[ 19] RET  _    0
    

PASS - nil
