DEBUG expanding frames of ctx, current size: 0

[Frame   0]
===========
> 07-loop-for-while.goblin (Func)
  Constants:
    [  0] "a" (String)
    [  1] 5 (Int)
    [  2] "sum" (String)
    [  3] 0 (Int)
    [  4] 1 (Int)

  Variables:
    a = 0 (Int)
    sum = 15 (Int)

  Stack:
    [  0] 15 (Int)
sp->[  1] [Nil]

  Instructions:
    [  9] PUSH V    0 ; var a
    [ 10] ADD  _    0
    [ 11] POP  V    2 ; var sum
    [ 12] PUSH V    0 ; var a
    [ 13] PUSH K    4 ; 1 (Int)
    [ 14] SUB  _    0
    [ 15] POP  V    0 ; var a
    [ 16] JMPB J   12
    [ 17] PUSH V    2 ; var sum
    [ 18] DUMP S    1
pc->[ 19] RET  _    0
    

PASS - 15
