DEBUG expanding frames of ctx, current size: 0
DEBUG expanding frames of ctx, current size: 1
DEBUG expanding frames of ctx, current size: 2
hi

[Frame   0]
===========
> 11-call-method.goblin (Func)
  Constants:
    [  0] "fmt" (String)
    [  1] "a" (String)
    [  2] "b" (String)
    [  3] "c" (String)
    [  4] "hi" (String)
    [  5] "you" (String)

  Variables:
    a = { "b" (String): a.b (Func),  "c" (String): "hi" (String), } (Object)
    fmt = { "Println" (String): fmt.Println (Func),  "Printf" (String): fmt.Printf (Func), } (Object)

  Stack:
    [  0] "hi,you" (String)
sp->[  1] [Nil]

  Instructions:
    [  7] SFLD _    0
    [  8] PUSH K    4 ; "hi" (String)
    [  9] PUSH K    3 ; "c" (String)
    [ 10] PUSH V    1 ; var a
    [ 11] SFLD _    0
    [ 12] PUSH K    5 ; "you" (String)
    [ 13] PUSH K    2 ; "b" (String)
    [ 14] PUSH V    1 ; var a
    [ 15] CFLD A    1
    [ 16] DUMP S    1
pc->[ 17] RET  _    0
    

PASS - hi,you
