DEBUG expanding frames of ctx, current size: 0
DEBUG expanding frames of ctx, current size: 1

[Frame   0]
===========
> 13-global-var.agora (Func)
  Constants:
    [  0] "a" (String)
    [  1] 5 (Int)
    [  2] "b" (String)
    [  3] 3 (Int)

  Variables:
    a = 8 (Int)
    b = b (Func)

  Stack:
    [  0] [Nil]
    [  1] 8 (Int)
sp->[  2] [Nil]

  Instructions:
    [  0] PUSH K    1 ; 5 (Int)
    [  1] POP  V    0 ; var a
    [  2] PUSH F    1 ; b (Func)
    [  3] POP  V    2 ; var b
    [  4] PUSH K    3 ; 3 (Int)
    [  5] PUSH V    2 ; var b
    [  6] CALL A    1
    [  7] PUSH V    0 ; var a
    [  8] DUMP S    1
pc->[  9] RET  _    0
    

PASS - 8
