DEBUG expanding frames of ctx, current size: 0
DEBUG expanding frames of ctx, current size: 1
DEBUG expanding frames of ctx, current size: 2
17 foo false

[Frame   0]
===========
> 14-args-array.goblin (Func)
  Constants:
    [  0] "fmt" (String)
    [  1] "f" (String)
    [  2] 17 (Int)
    [  3] "foo" (String)
    [  4] false (Bool)

  Variables:
    f = f (Func)
    fmt = { "Println" (String): fmt.Println (Func),  "Printf" (String): fmt.Printf (Func), } (Object)

  Stack:
    [  0] [Nil]
    [  1] [Nil]
sp->[  2] [Nil]

  Instructions:
    [  1] POP  V    0 ; var fmt
    [  2] PUSH F    1 ; f (Func)
    [  3] POP  V    1 ; var f
    [  4] PUSH K    2 ; 17 (Int)
    [  5] PUSH K    3 ; "foo" (String)
    [  6] PUSH K    4 ; false (Bool)
    [  7] PUSH V    1 ; var f
    [  8] CALL A    3
    [  9] PUSH N    0 ; [Nil]
    [ 10] DUMP S    1
pc->[ 11] RET  _    0
    

PASS - nil
