DEBUG expanding frames of ctx, current size: 0
DEBUG expanding frames of ctx, current size: 1
true

[Frame   0]
===========
> 08-if-else.agora (Func)
  Constants:
    [  0] "fmt" (String)
    [  1] "a" (String)
    [  2] "ok" (String)
    [  3] "Println" (String)
    [  4] "true" (String)
    [  5] "false" (String)

  Variables:
    a = "ok" (String)
    fmt = { "Println" (String): fmt.Println (Func),  "Printf" (String): fmt.Printf (Func), } (Object)

  Stack:
    [  0] 5 (Int)
    [  1] [Nil]
sp->[  2] [Nil]

  Instructions:
    [  7] PUSH K    3 ; "Println" (String)
    [  8] PUSH V    0 ; var fmt
    [  9] CFLD A    1
    [ 10] JMPF J    4
    [ 11] PUSH K    5 ; "false" (String)
    [ 12] PUSH K    3 ; "Println" (String)
    [ 13] PUSH V    0 ; var fmt
    [ 14] CFLD A    1
    [ 15] PUSH N    0 ; [Nil]
    [ 16] DUMP S    1
pc->[ 17] RET  _    0
    

PASS - nil
